spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate.show_sql: true
    hibernate:
      ddl-auto: none